MAIN_MENU_SCREEN_TITLE = "Menu principal"
MAIN_MENU_REGISTER_ORDER_OPTION = "Registrar ordem"
MAIN_MENU_LIST_ORDERS_OPTION = "Listar ordens"
MAIN_MENU_UPDATE_ORDER_OPTION = "Alterar ordem"
MAIN_MENU_CANCEL_ORDER_OPTION = "Cancelar ordem"
MAIN_MENU_EXIT_OPTION = "Sair"

REGISTER_ORDER_SCREEN_TITLE = "Registrar ordem"
